# Generated by Django 4.1.2 on 2022-10-19 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('preco', models.FloatField()),
                ('tempo_preparo_minutos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_media', models.FloatField()),
                ('proprietario', models.CharField(max_length=250)),
                ('localizacao', models.CharField(max_length=400)),
                ('nome', models.CharField(max_length=200)),
                ('qtd_funcionarios', models.IntegerField()),
                ('horario_funcionamento', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=25)),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('lista_itens', models.ManyToManyField(to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=256, null=True)),
                ('cpf', models.CharField(blank=True, max_length=25, null=True)),
                ('cargo', models.CharField(choices=[('G1', 'Gerente'), ('G2', 'Garçom')], max_length=3)),
                ('data_contrato', models.DateField()),
                ('salario', models.FloatField()),
                ('carga_horaria', models.FloatField()),
                ('avaliação', models.FloatField()),
                ('telefone', models.CharField(max_length=20)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.restaurante')),
            ],
        ),
    ]
