# Generated by Django 4.1.2 on 2022-10-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='avaliação',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='avaliacao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
