# Generated by Django 4.1.2 on 2022-10-19 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='avaliacao',
            field=models.FloatField(blank=True, null=True, verbose_name='Avaliação do Funcionário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='carga_horaria',
            field=models.FloatField(verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('G1', 'Gerente'), ('G2', 'Garçom')], max_length=3, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CPF do Funcionário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_contrato',
            field=models.DateField(verbose_name='Data de contrato'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nome do Funcionário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.FloatField(verbose_name='Salário Inicial'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone do Funcionário'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=256, verbose_name='Nome do Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='preco',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tempo_preparo_minutos',
            field=models.FloatField(verbose_name='Tempo de preparo(minutos)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.IntegerField(choices=[(0, 'Cartão de crédito'), (1, 'PIX'), (2, 'Dinheiro à vista')], default=2, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='lista_itens',
            field=models.ManyToManyField(to='core.item', verbose_name='Lista de Itens'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.IntegerField(verbose_name='Mesa N°'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='avaliacao_media',
            field=models.FloatField(verbose_name='Avaliação Média'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='cardapio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item', verbose_name='Cardápio'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='horario_funcionamento',
            field=models.CharField(max_length=100, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='localizacao',
            field=models.CharField(max_length=400, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='proprietario',
            field=models.CharField(max_length=250, verbose_name='Nome do Proprietário'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='qtd_funcionarios',
            field=models.IntegerField(verbose_name='Quantidade de Funcionários'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='telefone',
            field=models.CharField(max_length=25, verbose_name='Telefone do Restaurante'),
        ),
    ]
