# Generated by Django 4.1.2 on 2022-10-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_funcionario_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descricao',
            field=models.CharField(max_length=300, null=True, verbose_name='Descrição'),
        ),
    ]
