# Generated by Django 4.1.2 on 2022-10-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'permissions': [('pode_gerenciar_funcionarios', 'Pode gerenciar funcionários')]},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('pode_cadastrar_item', 'Pode cadastrar um novo item')]},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('pode_modificar_pedidos', 'Pode modificar pedidos')]},
        ),
    ]
