# Generated by Django 4.1.2 on 2022-10-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_funcionario_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='CPF do Funcionário'),
        ),
    ]
