# Generated by Django 4.1.2 on 2022-11-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='cardapio',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cardapio',
            field=models.ManyToManyField(to='core.item', verbose_name='Cardápio'),
        ),
    ]
