# Generated by Django 4.1.2 on 2022-11-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tem_usuario',
            field=models.BooleanField(default=False, verbose_name='Tem usuário ?'),
        ),
    ]
