# Generated by Django 4.1.2 on 2022-11-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_funcionario_tem_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='cardapio',
        ),
    ]
